name: Notify New Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  notify-dependent-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.DEP_UPDATE_APP_ID }}
          private_key: ${{ secrets.DEP_UPDATE_APP_PRIVATE_KEY }}

      - name: Trigger Repository B Update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: ptagl/test-rust-dep-b
          event-type: dependency-update
          client-payload: |
            {
              "dependency": "test-rust-dep-a",
              "version": "${{ github.ref_name }}"
            }
